apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-applicationset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters: {}
  template:
    metadata:
      name: 'nginx-app'
    spec:
      project: default
      source:
        repoURL: https://github.com/deependra-parmar/ArgoCD-Resources.git
        targetRevision: HEAD
        path: applicationset/prod
      destination:
        server: '{{.server}}'
        namespace: 'nginx-app'

        # For creating ns if not exists
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
      
        # Turn automatic deployment to on (POLLS EVERY 3 MINUTES)
        # If you don't want the delay, configure a GITHUB WEBHOOK
        automated:
          selfHeal: true # enable auto-sync to trigger when git repo is changed
          prune: true # to enable deleting the resources when a manifest is deleted.