apiVersion: v1
kind: Secret
metadata:
  name: argocd-cluster-secret
  labels:
    argocd.argoproj.io/secret-type: cluster
data:
  config: eyd0bHNDbGllbnRDb25maWcnOnsnaW5zZWN1cmUnOmZhbHNlfX0K
  name: Y2x1c3Rlcgo=
  server: aHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjCg==