apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-applicationset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://kubernetes.default.svc
      - cluster: stage
        url: https://kubernetes.default.svc
      - cluster: prod
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{.cluster}}-nginx-app'
    spec:
      project: default
      source:
        repoURL: https://github.com/deependra-parmar/ArgoCD-Resources.git
        targetRevision: HEAD
        path: applicationset/{{.cluster}}
      destination:
        server: '{{.url}}'
        namespace: '{{.cluster}}-nginx-app'

        # For creating ns if not exists
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
      
        # Turn automatic deployment to on (POLLS EVERY 3 MINUTES)
        # If you don't want the delay, configure a GITHUB WEBHOOK
        automated:
          selfHeal: true # enable auto-sync to trigger when git repo is changed
          prune: true # to enable deleting the resources when a manifest is deleted.